USE_FFTW3
#OUTPUT_POTENTIAL
#DM_SIDM=2
ALLOW_IMBALANCED_GASPARTICLELOAD

GALSF
#SELFGRAVITY_OFF
GRAVITY_ANALYTIC
ADM
EOS_GAMMA=(5.0/3.0)
COOLING
HYDRO_MESHLESS_FINITE_MASS
#GALSF_FB_MECHANICAL
#METALS
#MULTIPLEDOMAINS=64

# COSMOLOGICAL FLAGS
#USE_FFTW3
#HYDRO_MESHLESS_FINITE_MASS
#BOX_PERIODIC
#PMGRID=32
#PM_HIRES_REGION_CLIPPING=1000
#MULTIPLEDOMAINS=16
#ADAPTIVE_GRAVSOFT_FORGAS
