#define USE_FFTW3 
#define ALLOW_IMBALANCED_GASPARTICLELOAD 
#define OUTPUT_POSITIONS_IN_DOUBLE 
#define GALSF 
#define ADAPTIVE_GRAVSOFT_FORGAS 
#define ADM 
#define EOS_GAMMA (5.0/3.0)
#define HYDRO_MESHLESS_FINITE_MASS 
#define GALSF_SFR_VIRIAL_SF_CRITERION 0
#define GALSF_SFR_MOLECULAR_CRITERION 
#define GALSF_SFR_VIRIAL_SF_CRITERION_ADM 1
#define GALSF_FB_MECHANICAL 
#define METALS 
#define TURB_DIFF_METALS 
#define TURB_DIFF_METALS_LOWORDER 
#define GALSF_FB_FIRE_AGE_TRACERS 16
#define COOLING 
#define COOL_METAL_LINES_BY_SPECIES 
#define COOL_LOW_TEMPERATURES 
#define MULTIPLEDOMAINS 64
#define GALSF_FB_FIRE_STELLAREVOLUTION 2
#define GALSF_FB_FIRE_RT_HIIHEATING 
#define GALSF_FB_FIRE_RT_LOCALRP 
#define GALSF_FB_FIRE_RT_LONGRANGE 
#define GALSF_FB_FIRE_RT_UVHEATING 
