#define USE_FFTW3 
#define ALLOW_IMBALANCED_GASPARTICLELOAD 
#define GALSF 
#define ADAPTIVE_GRAVSOFT_FORGAS 
#define ADM 
#define EOS_GAMMA (5.0/3.0)
#define COOLING 
#define HYDRO_MESHLESS_FINITE_MASS 
#define GALSF_SFR_VIRIAL_SF_CRITERION 1
#define GALSF_FB_MECHANICAL 
#define METALS 
#define COOL_METAL_LINES_BY_SPECIES 
#define MULTIPLEDOMAINS 64
